---
- hosts: localhost
  connection: local
  become: true

  roles:
    - visual-studio-code
    - robertdebock.update

  tasks:  
    - name: Install packages
      become: true
      package:
        name: 
          - neofetch
          - neovim
          - kate
          - python3-pip
        state: present
    - name: Install Jupyter Lab
      become: false
      pip:
        name: 
          - jupyterlab
          - requests>2.22
          - ncclient
        extra_args: --user
    # - name: Creating install directories
    #   become: no
    #   command: mkdir $HOME/Documents/init_setup/{theme10d,theme10l,icon}  -p
    # - name: Clone Repo Win10 Dark Theme
    #   git:
    #     repo: 'https://github.com/yeyushengfan258/We10XOS-kde.git'
    #     dest: $HOME/Documents/init_setup/theme10d
    # - name: Clone Repo Win10 Dark Theme
    #   git:
    #     repo: 'https://github.com/yeyushengfan258/We10XOS-kde.git'
    #     dest: $HOME/Documents/init_setup/theme10l
    # - name: Clone Repo Win10 Dark Theme
    #   git:
    #     repo: 'https://github.com/yeyushengfan258/We10XOS-kde.git'
    #     dest: $HOME/Documents/init_setup/icon
    # - name: Install Themes and Icons
    #   become: no
    #   command: $HOME/Documents/init_setup/theme10d/install.sh && $HOME/Documents/init_setup/theme10l/install.sh && $HOME/Documents/init_setup/icon/install.sh -a
    # - name: Set Plasma Theme
    #   become: no
    #   command: lookandfeeltool --apply com.github.yeyushengfan258.We10XOS

