- hosts: localhost
  tasks:
    - name: Add VS Code Repo Key
      become: yes
      command: rpm --import https://packages.microsoft.com/keys/microsoft.asc
    - name: Add Repo
      become: yes
      command: sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
    - name: Install Visual Studio Code
      become: yes
      package:
        name: code-insiders
        state: present
    - name: Install neofetch
      become: yes
      package:
        name: neofetch
        state: present
    - name: Install neovim
      become: yes
      package:
        name: neovim
        state: present
    - name: Install pip
      become: yes
      package:
        name: python3-pip
        state: present
    - name: Install Kate
      become: yes
      package:
        name: kate
        state: present
    - name: Install git
      become: yes
      package:
        name: git
        state: present
    - name: Creating install directories
      become: no
      command: mkdir $HOME/Documents/init_setup/{theme10d,theme10l,icon}  -p
    - name: Clone Repos
      become: no
      command: git clone https://github.com/yeyushengfan258/We10XOS-kde.git $HOME/Documents/init_setup/theme10d && git clone https://github.com/yeyushengfan258/Win10Build-kde.git $HOME/Documents/init_setup/theme10l && git clone https://github.com/yeyushengfan258/We10X-icon-theme.git $HOME/Documents/init_setup/icon
    - name: Install Themes and Icons
      become: no
      command: $HOME/Documents/init_setup/theme10d/install.sh && $HOME/Documents/init_setup/theme10l/install.sh && $HOME/Documents/init_setup/icon/install.sh -a
    - name: Set Plasma Theme
      become: no
      command: lookandfeeltool --apply com.github.yeyushengfan258.We10XOS
    - name: Install Jupyter Lab
        pip:
          name: jupyterlab
          extra_args: --user
    - name: Install pyats
        pip:
          name: pyats
          extra_args: --user
    - name: Install requests
        pip:
          name: requests
          extra_args: --user
    - name: Install ncclient
        pip:
          name: ncclient
          extra_args: --user